### ISSUE TITLE
CentOS CI improvements

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd-centos-ci#36]
Let's keep track of things, which should (or could) be added to the CentOS CI.

#### Short term: ####
* [x] Rewrite `agent-control.py` (#37)
  * correctly return machines back to duffy on job fail/abort
* [x] Use the CentOS CI infrastructure for a copr repo mirror (https://github.com/systemd/systemd-centos-ci/pull/35#issuecomment-449668615), fixed in #88 & #89 
   * missing `createrepo` package on the systemd slave (https://bugs.centos.org/view.php?id=15643)
* [ ] Install and setup [dracut crypt SSH](https://github.com/dracut-crypt-ssh/dracut-crypt-ssh) (https://github.com/systemd/systemd-centos-ci/pull/31)
* [x] Attempt to fix [flaky tests](https://github.com/systemd/systemd-centos-ci/blob/master/agent/testsuite.sh#L41-L45)

#### Long term: ####
* [ ] Investigate fails in the Beakerlib testsuite
* [ ] Sync (and possibly upstream) the downstream Beakerlib testsuite

#### To consider: ####
* [x] Re-enable `systemd-networkd-tests.py` (https://github.com/systemd/systemd-centos-ci/issues/23)
* [x] Landing page with CI results (#39)

**Comment by mrc0mmand** [comment]
As the Jenkins configuration is missing in this repo and, yet it's as important as the scripts here, I tried to at least describe it in a wiki article, should it be needed in the future: https://github.com/systemd/systemd-centos-ci/wiki/Jenkins-Configuration

**Comment by mrc0mmand** [comment]
I closed the dracut SSH PR, as it didn't work as good as I'd like (for now), maybe I'll return to it in the future. The Beakerlib testsuite task is currently split into several RH/Fedora tasks, which are going to take some time:

- https://pagure.io/flock/issue/170
- several internal Jira tasks regarding migration to FMF as the metadata storage

**Comment by evverx** [comment]
@mrc0mmand I took a look at https://pagure.io/flock/issue/170 and my understanding is that the metadata is supposed to make it easier to run "the Beakerlib testsuite task" but I'm wondering what is going to happen to weird tests like the networkd test under ASan+UBsan or the "upstream" test (which I think are relatively hard to describe declaratively) on Fedora CI. It seems to me generally it would be best to get a pool of machines you can set up as you see fit.

**Comment by mrc0mmand** [comment]
> @mrc0mmand I took a look at https://pagure.io/flock/issue/170 and my understanding is that the metadata is supposed to make it easier to run "the Beakerlib testsuite task" but I'm wondering what is going to happen to weird tests like the networkd test under ASan+UBsan or the "upstream" test (which I think are relatively hard to describe declaratively) on Fedora CI.

The FMF is indeed primarily for Beakerlib tests, as in current form we have the metadata for each downstream test scattered around various internal services, which is pretty awful and mostly unportable.

> It seems to me generally it would be best to get a pool of machines you can set up as you see fit.

I wish, but this is pretty much next to impossible, at least in the Fedora infrastructure (right know I can't even get into touch with CentOS CI maintainers regarding the [resource limits](https://bugs.centos.org/view.php?id=16120)). I recently joined the new [Fedora CI SIG](https://fedoraproject.org/wiki/SIGs/CI) where one of the goals is to come up with a public CI system, so, hopefully, something relatively usable comes out from it. 

We could do *wonders* with just a pool of machines, but that seems to be a quite unpopular way of testing is today's world of containers :-)

**Comment by evverx** [comment]
By the way, generally I spend some time looking at different testing technologies and I wouldn't say Beakerlib is particularly popular. As far as I can remember, bekearlib was brought up just once (twice if we will count https://github.com/systemd/systemd/pull/12884) in the systemd repository in https://github.com/systemd/systemd/pull/5354 (where I was strongly opposed to Avocado Framework). I'm wondering if it's something internal that has to be used to leverage existing infrastructure or it has advantages over other testing frameworks.

**Comment by mrc0mmand** [comment]
That's true, it's not widely used out of RH and Fedora environments, as it was *home-brewed* in Red Hat as a replacement of the much older (RHTS) framework. That said, a particularly large portion of our internal automation (in RH) depends on Beakerlib and its (currently) scattered metadata -  the Makefile (used by Beakerlib) began to be really cumbersome to use for more complex metadata (relevancy across different products, hardware requirements, etc.), so some of the metadata moved to a different parts of the RH infrastructure, which lead to a ~~clusterf-~~ not a nice situation, preventing those tests to be upstreamed without plethora of kludges.

As several of the components trying to move the most of the testing to upstream (systemd is one of them), we finally managed to start an initiative, which focuses on replacing the all-over-the-place metadata with something more elegant.

During the initiative meetings I mentioned that with these unified metadata it shouldn't be an issue to run these tests both downstream and upstream (e.g. Fedora), thus the somewhat close relationship to the Fedora CI SIG :-)

**Comment by mrc0mmand** [comment]
It's also worth mentioning that by moving to the FMF (for metadata), the Beakerlib dependency should be much weaker, thus making space for other frameworks. In systemd (downstream) we have a few tests written in Avocado, yet they have to be wrapped in a Beakerlib *shell*, which is pretty ugly. After moving to FMF, this *shell* could be safely dropped.
